---
title: "PANCHANGE_plot_backup"
author: "Christopher Huebel"
date: "30/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
summary_data <- dat.long.gad.sum %>%
  group_by(Time_point) %>%
  summarise(
    mean = mean(gad.sum_score, na.rm = T),
    min = mean(gad.sum_score, na.rm = T) - qnorm(0.975)*sd(gad.sum_score, na.rm = T)/sqrt(n()),
    max = mean(gad.sum_score, na.rm = T) + qnorm(0.975)*sd(gad.sum_score, na.rm = T)/sqrt(n()),
    sd_low = mean(gad.sum_score, na.rm = T) - sd(gad.sum_score, na.rm = T),
    sd_up = mean(gad.sum_score, na.rm = T) + sd(gad.sum_score, na.rm = T)
  )

summary_data
```


```{r gad violin sum}
violin.gad.sum.prepan.retro <- dat.long.gad.sum %>%
  filter(Time_point != "base") %>%
  ggplot(mapping = aes(
    x = Full_cohort,
    y = gad.sum_score,
    fill = Time_point)) +
    geom_hline(yintercept = 5, linetype = "dashed", color = "gray") +
  geom_hline(yintercept = 10, linetype = "dashed", color = "gray") +
  geom_hline(yintercept = 15, linetype = "dashed", color = "gray") +
  geom_split_violin(
    trim = FALSE,
    alpha = 0.5
    ) +
 stat_summary(fun.y = mean,
               fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom = "pointrange",
              position = position_dodge(width = .25)) +
    labs(
    x = "GAD7 scores",
    y = "Percentage of participants",
    fill = "Time point") +
  theme_personal +
  scale_fill_manual(
    values = COPINGpalette3,
    breaks = c("prepan", "retro", "base"),
    labels = c("base" = "Baseline", "prepan" = "Prepandemic", "retro" = "Retrospective")
    )
violin.gad.sum.prepan.retro

violin.gad.sum.prepan.base <- dat.long.gad.sum %>%
  filter(Time_point != "retro") %>%
  ggplot(mapping = aes(
    x = Full_cohort,
    y = gad.sum_score,
    fill = Time_point)) +
    geom_hline(yintercept = 5, linetype = "dashed", color = "gray") +
  geom_hline(yintercept = 10, linetype = "dashed", color = "gray") +
  geom_hline(yintercept = 15, linetype = "dashed", color = "gray") +
  geom_split_violin(
    trim = FALSE,
    alpha = 0.5
    ) +
 stat_summary(fun.y = mean,
               fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom = "pointrange",
              position = position_dodge(width = .25)) +
  labs(
    x = "GAD7 scores",
    y = "Percentage of participants",
    fill = "Time point") +
  theme_personal +
  scale_fill_manual(
    values = COPINGpalette3,
    breaks = c("prepan", "retro", "base"),
    labels = c("base" = "Baseline", "prepan" = "Prepandemic", "retro" = "Retrospective")
    )
violin.gad.sum.prepan.base

violin.gad.sum.retro.base <- dat.long.gad.sum %>%
  filter(Time_point != "prepan") %>%
  ggplot(mapping = aes(
    x = Full_cohort,
    y = gad.sum_score,
    fill = Time_point)) +
    geom_hline(yintercept = 5, linetype = "dashed", color = "gray") +
  geom_hline(yintercept = 10, linetype = "dashed", color = "gray") +
  geom_hline(yintercept = 15, linetype = "dashed", color = "gray") +
  geom_split_violin(
    trim = FALSE,
    alpha = 0.5
    ) +
 stat_summary(fun.y = mean,
               fun.ymin = function(x) mean(x) - sd(x), 
               fun.ymax = function(x) mean(x) + sd(x), 
               geom = "pointrange",
              position = position_dodge(width = .25)) +
  labs(
    x = "GAD7 scores",
    y = "Percentage of participants",
    fill = "Time point") +
  theme_personal +
  scale_fill_manual(
    values = COPINGpalette3,
    breaks = c("prepan", "retro", "base"),
    labels = c("base" = "Baseline", "prepan" = "Prepandemic", "retro" = "Retrospective")
    )
violin.gad.sum.retro.base

violin.gad.sum.prepan.retro +
  violin.gad.sum.prepan.base +
  violin.gad.sum.retro.base +
  plot_layout(guides = "collect", widths = c(1,1,1)) +
  plot_annotation(tag_levels = "A")
```



```{r gad violin sum}
dat.long.gad.sum %>%
  filter(Time_point != "base") %>%
  ggplot(mapping = aes(
    x = Sample,
    y = gad.sum_score,
    fill = Time_point)) +
  geom_split_violin(
#    color = textcolor,
    trim = FALSE,
    alpha = 0.5
    ) +
  labs(
    x = "GAD7 scores",
    y = "Percentage of participants",
    fill = "Time point") +
  theme_personal +
  scale_fill_manual(
    values = COPINGpalette3,
    breaks = c("prepan", "retro", "base"),
    labels = c("base" = "Baseline", "prepan" = "Prepandemic", "retro" = "Retrospective")
    )+
  coord_flip()
```


```{r gad violin sum}
dat.long.gad.sum %>%
  filter(Time_point != "base") %>%
  ggplot(mapping = aes(
    x = Disorder_hierarchical,
    y = gad.sum_score,
    fill = Time_point)) +
  geom_split_violin(
#    color = textcolor,
    trim = FALSE,
    alpha = 0.5
    ) +
  labs(
    x = "GAD7 scores",
    y = "Percentage of participants",
    fill = "Time point") +
  theme_personal +
  scale_fill_manual(
    values = COPINGpalette3,
    breaks = c("prepan", "retro", "base"),
    labels = c("base" = "Baseline", "prepan" = "Prepandemic", "retro" = "Retrospective")
    )+
  coord_flip()
```

